name: Publish Package to npmjs
on:
 push:
  branches:
  - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
          # Defaults to the user or organization that owns the workflow file
          scope: '@octocat'
      - run: yarn
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}


# name: Publish
# on:
#  push:
#   branches:
#   - develop
# on: [push]
#     tags:
#       - v*.*.*
# jobs:
#   publish:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@master
#       - uses: actions/setup-node@v1
#         with:
#           node-version: 12
#           registry-url: https://registry.npmjs.org/
#       - run: yarn
#       - run: yarn publish
#         env:
#           NODE_AUTH_TOKEN: ${{ secrets.npm_token }}