name: Publish Package to npmjs
on:
 push:
   branches:
     - develop
jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
          # Defaults to the user or organization that owns the workflow file
          scope: '@octocat'
      - name: Install dependencies
      - run: yarn install
      - run: yarn build
      - name: publish to npm
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}

