name: Test Pull Request
on:
 pull_request:
   branches:
     - 'main'
   paths:
     - 'src/components/**/*.js'
     - 'src/components/**/*.ts'
     - 'src/components/**/*.tsx'
     - 'src/components/**/*.scss'
     - 'src/components/**/*.css'
jobs:
  Test-Pull-Request:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn test
